servers:
  server:
    port: 25565
    host: example.org
  another:
    port: 25565
    host: 192.168.0.1
    version: 1.5
    description: You can add as many additional attributes as you need

discord:
  token: xxxxxxxxxxxxxxx
  client_id: xxxxxxxxxxxxx
  prefix: ':'
